sf.consumerKey=YOUR_KEY
sf.consumerSecret=YOUR_SECRET
sf.username=YOUR_USERNAME
sf.password=YOUR_PASSWORD
sf.securityToken=YOUR_TOKEN
sf.tokenEndpoint=https://login.salesforce.com/services/oauth2/token